### ISSUE TITLE
AsyncAPI spec v3 support in Go watermill template

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/go-watermill-template#243]
#### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

Remaining tasks:

- [ ] Update template to use parser v2, this is already supported by the [generator by changing the `apiVersion`](https://github.com/asyncapi/generator/blob/master/docs/configuration-file.md)
- [ ] Update Modelina dependency once released - https://github.com/asyncapi/modelina/issues/1376

**Comment by Shurtu-gal** [comment]
@jonaslagoni should this be reopened?
